travis:
  secure:
    BINSTAR_TOKEN: bLpThvg9BzkqhcrkGOHkLlCCCdiooku8qa3LXevhO3Kw0d3xnPNqgJ8EFzrm9nkMJc28Z1JGcBcGuugXpphKQR4hEF210vqTEENelZmaThM2svkDUj1il/xI1BGvJ0hLV0VIc0Y0pzrcG3tduAxwt97+Qx34wVMk2i8mOJUfCSGEk0dDgtECxpRSyrrwV7vzvj9TbiEc8pJtKqEYV3K2XpA4qKV7vAHswvsQ+9cR1XQseMe9fYgc13XrYZZ6srCJb166pLdc03hQHltuo7c2/9z78kuXQl6p31Fqm9sK99JKRlkU3fExH9rFyfYxfF5+l65jiavkDtoRz4GFpjyuVX914CgtA2h/yuau61U7LiPwU8SHdEwQCp2WnQ7mV81kuV3b5NgB4gGj5iZVOu+QW6I3hD6XaqkwxSI3FFotA3G249r3g7HRJBKEqZp+37pSAX3tyDNoLDYVHSMGTZg+n/q5uwFbR5tFbe6je8ndPHMghXc8nCsTK7HZvGPKoLgWH+wQMcooiiZc5FyIb7yAye6Y2U1BC5oZ4KbyUg37qudZ3B8rKLnT5Hf3ohoEsmPdpKbtsgZP8Voja93B00D0V8YJNpeA0mlebTFldJGWJ/YGCUsRKkyzva8pqqnCBM2e3bBL8mTcpfIsh35ozUnX6bG5SY9xgIHqQ41Go+EifPM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
